-- APPROVED REQUESTS VIEW
DROP VIEW IF EXISTS VW_NUMBER_OF_APPROVED_REQUESTS;
CREATE VIEW VW_NUMBER_OF_APPROVED_REQUESTS AS SELECT * FROM request_state WHERE status = 1;

-- REJECTED REQUESTS VIEW
DROP VIEW IF EXISTS VW_NUMBER_OF_REJECTED_REQUESTS;
CREATE VIEW VW_NUMBER_OF_REJECTED_REQUESTS AS SELECT * FROM request_state WHERE status = 0;

-- PENDING REQUESTS VIEW
DROP VIEW IF EXISTS VW_NUMBER_OF_PENDING_REQUESTS;
CREATE VIEW VW_NUMBER_OF_PENDING_REQUESTS AS SELECT * FROM data_requests 
WHERE request_id NOT IN (
  SELECT request_id
  FROM request_state
);

-- RESEARCH PURPOSE REQUESTS VIEW
DROP VIEW IF EXISTS VW_NUMBER_OF_RESEARCH_REQUESTS;
CREATE VIEW VW_NUMBER_OF_RESEARCH_REQUESTS AS SELECT * FROM data_requests WHERE purpose_id = 1;

-- CONTINUITY OF CARE PURPOSE REQUESTS VIEW
DROP VIEW IF EXISTS VW_NUMBER_OF_CONTINUITY_OF_CARE_REQUESTS;
CREATE VIEW VW_NUMBER_OF_CONTINUITY_OF_CARE_REQUESTS AS SELECT * FROM data_requests WHERE purpose_id = 2;

-- OTHER PURPOSE REQUESTS VIEW
DROP VIEW IF EXISTS VW_NUMBER_OF_OTHER_PURPOSE_REQUESTS;
CREATE VIEW VW_NUMBER_OF_OTHER_PURPOSE_REQUESTS AS SELECT * FROM data_requests WHERE purpose_id = 3;