# Generated by Django 4.2.7 on 2024-07-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_is_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SourceCustodian',
        ),
    ]
