# Generated by Django 4.2.7 on 2024-07-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_sourcecustodian'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataCustodian',
        ),
    ]
