# Generated by Django 4.2.7 on 2024-07-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_datacustodian'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgrolestatus',
            name='Reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
