# Generated by Django 4.1 on 2023-09-25 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('filter_id', models.AutoField(primary_key=True, serialize=False)),
                ('filter_type', models.CharField(max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'filters',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('preset_id', models.AutoField(primary_key=True, serialize=False)),
                ('preset_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'presets',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VariableFilter',
            fields=[
                ('variable_filter_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data_exploration.filter')),
                ('var_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data_dictionary.variable')),
            ],
            options={
                'db_table': 'variable_filters',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PresetFilter',
            fields=[
                ('preset_filter_id', models.AutoField(primary_key=True, serialize=False)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data_exploration.filter')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data_exploration.preset')),
            ],
            options={
                'db_table': 'preset_filter',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PresetVariable',
            fields=[
                ('preset_variable_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_distinct', models.BooleanField()),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data_exploration.preset')),
                ('var', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data_dictionary.variable')),
            ],
            options={
                'db_table': 'preset_variables',
                'managed': True,
                'unique_together': {('preset', 'var')},
            },
        ),
    ]
