# Generated by Django 4.1 on 2023-10-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequest',
            name='ethics_committee_name',
            field=models.TextField(default=False),
        ),
    ]
