# Generated by Django 4.1 on 2023-10-19 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_requests', '0003_datahandlingdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffShared',
            fields=[
                ('staff_shared_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255)),
                ('identification_type', models.CharField(choices=[('Passport', 'Passport'), ('National ID', 'National ID'), ('None', 'None')], max_length=50)),
                ('identification_number', models.CharField(blank=True, max_length=30, null=True)),
                ('position_in_organisation', models.CharField(max_length=265)),
                ('confidentiality_protocols', models.BooleanField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_requests.datarequest')),
            ],
            options={
                'db_table': 'staff_shared',
                'managed': True,
            },
        ),
    ]
