# Generated by Django 4.1 on 2023-11-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_requests', '0004_staffshared'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequest',
            name='data_format',
            field=models.CharField(choices=[('Paper-based', 'Paper-based'), ('Electronic', 'Electronic'), ('Direct access', 'Direct access')], default='Electronic', max_length=65),
        ),
        migrations.AddField(
            model_name='datarequest',
            name='direct_access_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datarequest',
            name='direct_access_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datarequest',
            name='no_date_limit',
            field=models.BooleanField(default=False),
        ),
    ]
