# Generated by Django 4.1 on 2023-11-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_requests', '0005_datarequest_data_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequest',
            name='principal_email',
            field=models.CharField(default='requester@idarp.mw', max_length=255),
        ),
        migrations.AddField(
            model_name='datarequest',
            name='principal_fname',
            field=models.CharField(default='N/A', max_length=70),
        ),
        migrations.AddField(
            model_name='datarequest',
            name='principal_institution',
            field=models.CharField(default='Data Requester', max_length=255),
        ),
        migrations.AddField(
            model_name='datarequest',
            name='principal_occupation',
            field=models.CharField(default='Data Requester', max_length=255),
        ),
        migrations.AddField(
            model_name='datarequest',
            name='principal_phone',
            field=models.CharField(default='+265000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='datarequest',
            name='principal_sname',
            field=models.CharField(default='N/A', max_length=70),
        ),
    ]
