# Generated by Django 4.2.7 on 2023-11-28 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('data_requests', '0006_datarequest_principal_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('authored_on', models.DateTimeField(auto_now_add=True)),
                ('section', models.CharField(max_length=255)),
                ('resolved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.assignedrole')),
                ('request_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_requests.requeststate')),
            ],
            options={
                'db_table': 'state_comments',
                'managed': True,
            },
        ),
    ]
