# Generated by Django 4.2.7 on 2023-11-28 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('data_requests', '0007_statecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('reply', models.TextField()),
                ('responded_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.assignedrole')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_requests.statecomment')),
            ],
            options={
                'db_table': 'replies',
                'managed': True,
            },
        ),
    ]
