# Generated by Django 4.2.7 on 2024-01-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_requests', '0009_statecomment_data_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('equipment_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'equipment_types',
                'managed': True,
            },
        ),
    ]
