# Generated by Django 4.2.7 on 2024-01-22 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_requests', '0010_equipmenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='datahandlingdevice',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data_requests.equipmenttype'),
        ),
    ]
