# Generated by Django 4.2.7 on 2024-01-22 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_requests', '0011_datahandlingdevice_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahandlingdevice',
            name='equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='data_requests.equipmenttype'),
            preserve_default=False,
        ),
    ]
