# Generated by Django 4.2.7 on 2024-01-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_requests', '0012_alter_datahandlingdevice_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRB',
            fields=[
                ('irb_id', models.AutoField(primary_key=True, serialize=False)),
                ('irb_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'IRBs',
                'managed': True,
            },
        ),
    ]
