# Generated by Django 4.2.7 on 2024-01-22 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_requests', '0013_irb'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequest',
            name='irb_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data_requests.irb'),
        ),
    ]
