# Generated by Django 4.2.7 on 2024-01-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_requests', '0014_datarequest_irb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequest',
            name='additional_IRB_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datarequest',
            name='additional_ethics_committee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
