# Generated by Django 4.2.7 on 2024-01-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_requests', '0015_datarequest_additional_irb_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequest',
            name='irb_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='data_requests.irb'),
            preserve_default=False,
        ),
    ]
