# Generated by Django 4.2.7 on 2024-01-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_requests', '0016_alter_datarequest_irb_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datarequest',
            old_name='irb_id',
            new_name='irb',
        ),
    ]
