# Generated by Django 4.2.7 on 2024-01-26 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_requests', '0019_staffshared_identification_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datarequest',
            old_name='irb',
            new_name='ethics_committee',
        ),
        migrations.RemoveField(
            model_name='datarequest',
            name='ethics_committee_name',
        ),
    ]
