# Generated by Django 4.2.7 on 2024-01-26 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_requests', '0020_rename_irb_datarequest_ethics_committee_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='irb',
            table='irbs',
        ),
    ]
