# Generated by Django 4.2.7 on 2024-01-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_requests', '0021_alter_irb_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datahandlingdevice',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='datahandlingdevice',
            name='equipment_type',
        ),
    ]
