# Generated by Django 4.2.7 on 2024-01-26 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_requests', '0022_remove_datahandlingdevice_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datahandlingdevice',
            name='equipment_name',
            field=models.CharField(default='No Equipment Name', max_length=255),
        ),
        migrations.AddField(
            model_name='datahandlingdevice',
            name='equipment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='data_requests.equipmenttype'),
        ),
    ]
