# Generated by Django 4.2.7 on 2024-03-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_requests', '0028_alter_staffshared_identification_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='datahandlingdevice',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffshared',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
