# Verion of docker-compose to use 
version: "3"

services:
  django_api:
    container_name: cdr_ids_api
    build:
      context: . #Sets the directory for docker-compose to build.

    # Maps port on the local machine to port on Docker image
    ports:
      - "8000:8000"

    networks:
      - network
      
    volumes: 
    # Copy changes made to the project to your image in real-time.
      - .:/django_api
    # Handles the command used to run the project in the Docker container.
    command: sh -c "python manage.py runserver 0.0.0.0:8000" 
    # The environment variable credetials that is needed 
    environment:
      - DB_HOST=172.20.0.2
      - DB_NAME=cdr
      - DB_USER=admin
      - DB_PASS=password
      - DB_PORT=3306

networks:
  network:
    name: network
    external: true