# Generated by Django 4.2.7 on 2023-11-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('site_id', models.IntegerField(unique=True)),
                ('facility', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('partner_name', models.CharField(max_length=255)),
                ('site_name', models.CharField(max_length=255)),
                ('emr_type', models.CharField(max_length=255)),
                ('funding_agency', models.CharField(max_length=255)),
                ('cdc_region', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('orgunit', models.CharField(max_length=255)),
                ('date_synced', models.DateTimeField()),
            ],
            options={
                'db_table': 'facilities',
                'managed': True,
            },
        ),
    ]
