# Generated by Django 4.2.7 on 2023-11-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='district',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
