# Generated by Django 4.2.7 on 2023-11-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='date_synced',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
