# Generated by Django 4.2.7 on 2024-01-31 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackPhotos',
            fields=[
                ('feedback_photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_file_path', models.TextField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedback')),
            ],
            options={
                'db_table': 'feedback_photos',
                'managed': True,
            },
        ),
    ]
