# Generated by Django 4.2.7 on 2024-01-31 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedbackphotos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedbackPhotos',
            new_name='FeedbackPhoto',
        ),
    ]
