# Generated by Django 4.2.7 on 2024-01-12 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('setting', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=255)),
                ('default_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('user_setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('setting_value', models.CharField(max_length=255)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.setting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
