# Generated by Django 4.2.7 on 2024-01-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usersetting',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='setting',
            table='settings',
        ),
        migrations.AlterModelTable(
            name='usersetting',
            table='user_settings',
        ),
    ]
