# Generated by Django 4.1 on 2023-09-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dependencies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('edge_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'edges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InputValue',
            fields=[
                ('val_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'input_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('syn_id', models.AutoField(primary_key=True, serialize=False)),
                ('synonym', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'synonyms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('tbl_id', models.AutoField(primary_key=True, serialize=False)),
                ('tbl_name', models.CharField(max_length=65)),
                ('tbl_description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=30, null=True)),
                ('color', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'tables',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimelineOfChange',
            fields=[
                ('change_id', models.AutoField(primary_key=True, serialize=False)),
                ('change_date', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'timeline_of_change',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=65)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField()),
                ('active', models.IntegerField()),
            ],
            options={
                'db_table': 'topics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopicTable',
            fields=[
                ('tt_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_on', models.DateTimeField()),
                ('pos_x', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pos_y', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'topic_tables',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('var_id', models.AutoField(primary_key=True, serialize=False)),
                ('ids_column_name', models.CharField(db_column='IDS_column_name', max_length=65)),
                ('var_name', models.CharField(max_length=255)),
                ('data_type', models.CharField(blank=True, max_length=35, null=True)),
                ('meaning', models.TextField(blank=True, null=True)),
                ('date_introduced', models.DateField()),
                ('range', models.CharField(blank=True, max_length=30, null=True)),
                ('old_var_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.IntegerField(blank=True, null=True)),
                ('derived', models.BooleanField(blank=True, null=True)),
                ('usage', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'variables',
                'managed': False,
            },
        ),
    ]
