# Generated by Django 4.1 on 2023-09-25 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('palette_id', models.AutoField(primary_key=True, serialize=False)),
                ('palette_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'color_palettes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('data_source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_source',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PalettePosition',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'palette_positions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('tbl_id', models.AutoField(primary_key=True, serialize=False)),
                ('tbl_name', models.CharField(max_length=65)),
                ('tbl_description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=60, null=True)),
                ('entity_name', models.CharField(max_length=30, null=True)),
                ('in_PoC', models.BooleanField(null=True)),
                ('in_eMC', models.BooleanField(null=True)),
                ('poc_earliest_record', models.DateField(blank=True, null=True)),
                ('emc_earliest_record', models.DateField(blank=True, null=True)),
                ('poc_latest_record', models.DateField(blank=True, null=True)),
                ('emc_latest_record', models.DateField(blank=True, null=True)),
                ('poc_total_records', models.IntegerField(blank=True, null=True)),
                ('emc_total_records', models.IntegerField(blank=True, null=True)),
                ('poc_valid_records', models.IntegerField(blank=True, null=True)),
                ('emc_valid_records', models.IntegerField(blank=True, null=True)),
                ('publish', models.BooleanField(null=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data_dictionary.datasource')),
            ],
            options={
                'db_table': 'tables',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=65)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('active', models.IntegerField()),
            ],
            options={
                'db_table': 'topics',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('var_id', models.AutoField(primary_key=True, serialize=False)),
                ('ids_column_name', models.CharField(db_column='IDS_column_name', max_length=65)),
                ('var_name', models.CharField(max_length=255)),
                ('data_type', models.CharField(blank=True, max_length=35, null=True)),
                ('meaning', models.TextField(blank=True, null=True)),
                ('date_introduced', models.DateField()),
                ('range', models.CharField(blank=True, max_length=30, null=True)),
                ('old_var_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.IntegerField(blank=True, null=True)),
                ('derived', models.BooleanField(blank=True, null=True)),
                ('usage', models.CharField(blank=True, max_length=30, null=True)),
                ('is_primary', models.BooleanField(blank=True, default=False, null=True)),
                ('is_foreign', models.BooleanField(blank=True, default=False, null=True)),
                ('tbl', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='var', to='data_dictionary.table')),
            ],
            options={
                'db_table': 'variables',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TimelineOfChange',
            fields=[
                ('change_id', models.AutoField(primary_key=True, serialize=False)),
                ('change_date', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('var', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='timeline_of_changes', to='data_dictionary.variable')),
            ],
            options={
                'db_table': 'timeline_of_change',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TableType',
            fields=[
                ('table_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='palette_positions', to='data_dictionary.paletteposition')),
            ],
            options={
                'db_table': 'table_types',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='table',
            name='table_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='table_types', to='data_dictionary.tabletype'),
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('syn_id', models.AutoField(primary_key=True, serialize=False)),
                ('synonym', models.CharField(max_length=255)),
                ('var', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='synonyms', to='data_dictionary.variable')),
            ],
            options={
                'db_table': 'synonyms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InputValue',
            fields=[
                ('val_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('var', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='input_values', to='data_dictionary.variable')),
            ],
            options={
                'db_table': 'input_values',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_hex', models.CharField(max_length=10)),
                ('pallete', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='color_palettes', to='data_dictionary.colorpalette')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='color_positions', to='data_dictionary.paletteposition')),
            ],
            options={
                'db_table': 'colors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TopicTable',
            fields=[
                ('tt_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_on', models.DateTimeField()),
                ('pos_x', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pos_y', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tbl', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data_dictionary.table')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tables', to='data_dictionary.topic')),
            ],
            options={
                'db_table': 'topic_tables',
                'managed': True,
                'unique_together': {('topic', 'tbl')},
            },
        ),
        migrations.CreateModel(
            name='TableMetadata',
            fields=[
                ('metadata_id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=70)),
                ('value', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=70)),
                ('tbl', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data_dictionary.table')),
            ],
            options={
                'db_table': 'table_metadata',
                'managed': True,
                'unique_together': {('tbl', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('edge_id', models.AutoField(primary_key=True, serialize=False)),
                ('destination', models.ForeignKey(db_column='destination', on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrow_head', to='data_dictionary.table')),
                ('source', models.ForeignKey(db_column='source', on_delete=django.db.models.deletion.DO_NOTHING, to='data_dictionary.table')),
            ],
            options={
                'db_table': 'edges',
                'managed': True,
                'unique_together': {('source', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('depend_on', models.ForeignKey(db_column='depend_on', on_delete=django.db.models.deletion.DO_NOTHING, related_name='points_to', to='data_dictionary.variable')),
                ('var', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dependencies', to='data_dictionary.variable')),
            ],
            options={
                'db_table': 'dependencies',
                'managed': True,
                'unique_together': {('var', 'depend_on')},
            },
        ),
    ]
