# Generated by Django 4.1 on 2023-10-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='value_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
