# Generated by Django 4.1 on 2023-10-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_dictionary', '0003_variable_is_identifiable'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='db_host',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='db_password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='db_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='db_username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='dbms',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
