# Generated by Django 4.2.7 on 2024-02-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_dictionary', '0004_datasource_db_host_datasource_db_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='is_analytical',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
