# Generated by Django 4.2.7 on 2024-02-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_dictionary', '0005_variable_is_analytical'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablemetadata',
            old_name='type',
            new_name='val_type',
        ),
    ]
