# Generated by Django 4.2.7 on 2024-03-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_dictionary', '0007_variablemetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablemetadata',
            name='value',
            field=models.TextField(),
        ),
    ]
