# Generated by Django 4.2.7 on 2024-06-11 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_dictionary', '0008_alter_variablemetadata_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='enumerated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='variablemetadata',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='variable_metadata', to='data_dictionary.variable'),
        ),
    ]
