# Generated by Django 4.2.7 on 2024-07-02 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_datacustodian'),
        ('data_dictionary', '0009_variable_enumerated_alter_variablemetadata_variable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCustodian',
            fields=[
                ('custodian_id', models.AutoField(primary_key=True, serialize=False)),
                ('broker', models.BooleanField()),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data_dictionary.datasource')),
                ('org_role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.orgrole')),
            ],
            options={
                'db_table': 'data_custodians',
                'managed': True,
                'unique_together': {('data_source', 'org_role')},
            },
        ),
    ]
