# Generated by Django 4.2.7 on 2024-07-02 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_datacustodian'),
        ('data_dictionary', '0010_datacustodian'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('version_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('commited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_role', to='users.assignedrole')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_source', to='data_dictionary.datasource')),
            ],
            options={
                'db_table': 'versions',
                'managed': True,
            },
        ),
    ]
