from django.urls import path
from . import views

urlpatterns = [
    path('', views.UserList.as_view()),
    path('<int:pk>/', views.UserDetail.as_view()),
    path('detailuser/', views.GetUpdatedUserDetails.as_view()),
    path('signin/', views.SignInView.as_view(), name='signin'),
    path('signup/', views.SignUpOtpView.as_view(), name='signup'),
    path('assign-roles/', views.AssignRoleView.as_view(), name='assign-roles'),
    path('assigned-roles/approve/', views.AssignRoleApprovingView.as_view(), name='assigned-roles-approve'),
    path('role-statuses/', views.RoleStatusListView.as_view(), name='roles-statuses'),
    path('verify/', views.SignUpOtpVerificationView.as_view(), name='verify'),
    path('verify/resend', views.OtpResendView.as_view(), name='verify-resend'),
    path('organizations/', views.OrganizationList.as_view(), name='organizations'),
    path('organizations/<int:pk>/roles', views.OrganizationRoles.as_view(), name='org-roles'),
    path('track/', views.Track.as_view(), name='track'),
    path('generate-uuid/', views.GenerateUUID.as_view(), name='generate-uuid'),
    path('test/', views.TestView.as_view(), name='test'),
    path('organization-users/', views.OrganizationUserList.as_view(), name='organisation-user-list'),
    path('activate/<int:pk>/', views.UserActivationView.as_view(), name='user-activate'),
    path('phone/', views.CheckPhoneNumber.as_view(), name='phone-check'),
    path('duplicate/', views.IsADuplicatePhoneNumber.as_view(), name='duplicate-phone-check'),
    path('duplicate-email/', views.IsADuplicateEmailAddress.as_view(), name='duplicate-email-check'),
    path('forgot-password', views.ForgotPasswordView.as_view(), name='forgot-password'),
    path('validate-email/', views.ValidateEmailView.as_view(), name='validate_email'),
    path('update-user-email/', views.UpdateUserEmailView.as_view(), name='update_user_email'),
    path('update-user-phone/', views.UpdateUserPhoneView.as_view(), name='update_user_phone'),
    path('verify-otp/', views.VerifyOTP.as_view(), name='verify_otp'),
    path('setting-otp/', views.SendOTPBasedOnSettingAppView.as_view(), name='setting-otp'),
    path('update_profile/<int:pk>/', views.UserProfileUpdateView.as_view(), name='user-profile-update'),
    path('assigned-role-status/', views.AssignedRoleStatusListView.as_view(), name='assigned-role-status-list'),
    path('assigned-role-status/<int:pk>/', views.AssignedRoleStatusPatchView.as_view(), name='assigned-role-status-patch'),
]
