# Generated by Django 4.2.7 on 2024-03-11 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_dictionary', '0007_variablemetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proportion',
            fields=[
                ('proportion_id', models.AutoField(primary_key=True, serialize=False)),
                ('proportion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proportions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('snapshot_id', models.AutoField(primary_key=True, serialize=False)),
                ('as_of', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'snapshots',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VariableLevelCheck',
            fields=[
                ('vld_id', models.AutoField(primary_key=True, serialize=False)),
                ('dqa_check_id', models.IntegerField(unique=True)),
                ('description', models.TextField()),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_dictionary.variable')),
            ],
            options={
                'db_table': 'variable_level_checks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('numerator', models.IntegerField(default=0)),
                ('denominator', models.IntegerField(default=0)),
                ('proportion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dqa_snapshots.proportion')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dqa_snapshots.snapshot')),
            ],
            options={
                'db_table': 'results',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='proportion',
            name='variable_level_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dqa_snapshots.variablelevelcheck'),
        ),
    ]
