# Generated by Django 4.1 on 2023-09-26 14:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notifications',
            new_name='RequestNotification',
        ),
        migrations.AlterModelTable(
            name='requestnotification',
            table='request_notifications',
        ),
    ]
