# Generated by Django 4.1 on 2023-09-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_notifications_requestnotification_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestNotification',
        ),
    ]
