# Generated by Django 4.1 on 2023-09-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0003_delete_requestnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(default='Hello, You have unread iDARP Notifications')),
                ('authored_on', models.DateTimeField(auto_now=True)),
                ('read', models.BooleanField(default=False)),
                ('notification_type', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'managed': True,
            },
        ),
    ]
