# Generated by Django 4.1 on 2023-09-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_requests', '0001_initial'),
        ('notifications', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestNotification',
            fields=[
                ('request_notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_notification_type', models.CharField(blank=True, max_length=255, null=True)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification')),
                ('request_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_requests.requeststate')),
            ],
            options={
                'db_table': 'request_notifications',
                'managed': True,
            },
        ),
    ]
