# Generated by Django 4.1 on 2023-09-26 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('notifications', '0006_usernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupNotification',
            fields=[
                ('group_notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.orgrole')),
                ('request_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_request', to='notifications.requestnotification')),
            ],
            options={
                'db_table': 'group_notifications',
                'managed': True,
            },
        ),
    ]
